# Test password for local development
password = "test123"

# Supabase credentials
SUPABASE_URL = "https://ozusfgnnzanaxpcfidbm.supabase.co"
SUPABASE_KEY = "sb_publishable_PyVKM3BdygFWVdeZrirAVA_AxZFyNAA"
